# MULTINOMIAL NAIVE BAYES THEOREM PREDECTION WETHER THE MAIL IS SPAM OR HAM

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split



In [4]:
from sklearn.naive_bayes import MultinomialNB


In [8]:
df=pd.read_csv("E:/ppts/machine learning/15-naive-bayes/smsspamcollection/SMSSpamCollection",sep='\t',names=['Status', 'Message'])
df

Status                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
df.head()



Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
len(df[df.Status=='spam']) 

747

In [13]:
len(df[df.Status=='ham'])

4825

In [14]:
df.loc[df["Status"]=='spam', "Status"]=0
df.loc[df["Status"]=='ham', "Status"]=1

In [15]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [16]:
x = df["Message"]
y = df["Status"]

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [26]:
cv = CountVectorizer()
x_traincv = cv.fit_transform(x_train)
x_testcv = cv.transform(x_test)


In [27]:
mnb = MultinomialNB()


In [30]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [31]:
mnb.score(x_testcv, y_test)

0.9901345291479821

In [32]:
x_test.iloc[0]

'Yep, by the pretty sculpture'

In [33]:
pred = mnb.predict(x_testcv[0])
pred 

array([1])

In [38]:
# take another email and predict if it is spam or ham
x_test.iloc[31]
pred = mnb.predict(x_testcv[31])
pred 

array([1])

In [35]:
examples = ['Free viagra now', 'Hi, can we play golf tomorrow?']
test = cv.transform(examples)

In [36]:
test

<2x7711 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [37]:
pred = mnb.predict(test)

In [39]:
pred

array([1])